(()=>{
const $=s=>document.querySelector(s),G=window.V12_GEO;
const nav=document.createElement('nav');nav.className='phone-nav';nav.setAttribute('aria-label','Phone navigation');nav.innerHTML='<button data-view="map" aria-pressed="true">Map</button><button data-view="board" aria-pressed="false">Arrivals</button><button data-view="plan">Journey</button><button data-view="data">Data</button>';document.body.append(nav);
function view(which){document.body.classList.remove('phone-options');document.querySelector('#phoneOptions')?.setAttribute('aria-expanded','false');document.body.dataset.phoneView=which;nav.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===which)))}
document.addEventListener('station-board-open',()=>view('board'));
nav.onclick=e=>{const v=e.target.dataset.view;if(v==='plan')$('#journeyBtn').click();else if(v==='data')openData();else if(v){view(v);if(v==='board')$('#boardTab').click()}};
const optionsButton=document.createElement('button');optionsButton.id='phoneOptions';optionsButton.textContent='Options';optionsButton.setAttribute('aria-expanded','false');optionsButton.onclick=()=>{const on=document.body.classList.toggle('phone-options');optionsButton.setAttribute('aria-expanded',String(on))};$('.topbar').append(optionsButton);
const toolbar=$('.explore-bar');const doorButton=document.createElement('button');doorButton.textContent='Exit & door';doorButton.onclick=openDoor;toolbar.append(doorButton);
const dataButton=document.createElement('button');dataButton.textContent='Prediction data';dataButton.onclick=openData;toolbar.append(dataButton);
function dialog(id,title){let d=document.createElement('dialog');d.id=id;d.className='passenger-dialog';d.innerHTML=`<form method="dialog"><h2>${title}</h2><button aria-label="Close ${title}">×</button></form><div class="passenger-content"></div>`;document.body.append(d);return d}
const door=dialog('doorAdvisor','Exit & door'),data=dialog('dataPanel','Prediction data');
const options=Object.entries(G.stations).sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([c,s])=>`<option value="${c}">${s.name}</option>`).join('');
door.querySelector('.passenger-content').innerHTML=`<p>Exact door guidance is available only when a platform-specific mapping is recorded. Save a trusted Fast Exit recommendation for your route below.</p><label>Starting station<select id="doorFrom">${options}</select></label><label>Destination station<select id="doorTo">${options}</select></label><label>Exit letter / number<input id="doorExit" value="F" maxlength="12" placeholder="e.g. F"></label><button id="doorCheck">Check boarding guidance</button><div id="doorResult" aria-live="polite"></div><details><summary>Save a personal boarding note</summary><label>Arrival platform<input id="doorPlatform" maxlength="12" placeholder="e.g. 3"></label><label>Car and door from MTR Fast Exit<input id="doorNumber" maxlength="80" placeholder="Enter the recommendation you checked"></label><button type="button" id="doorSave">Save on this device</button><p id="doorSaved" role="status"></p></details>`;
$('#doorFrom').value='MKK';$('#doorTo').value='ADM';
function openDoor(){door.showModal();doorResult()}
function doorResult(){const from=$('#doorFrom').value,to=$('#doorTo').value,exit=$('#doorExit').value.trim().toUpperCase(),r=$('#doorResult');r.replaceChildren();let p=document.createElement('p');p.textContent=`${G.stations[from].name} → ${G.stations[to].name} · Exit ${exit||'not selected'}`;r.append(p);let saved=null;try{saved=JSON.parse(localStorage.getItem('boarding-note:'+from+':'+to+':'+exit)||'null')}catch{}if(saved){const own=document.createElement('p');own.textContent=`Your saved note: platform ${saved.platform}, ${saved.door}. Personal note, not independently verified.`;r.append(own)}let note=document.createElement('p');note.textContent=from===to?'Select a different destination for a train journey.':!exit?'Enter your destination exit.':'Car and door mapping is not verified in this app. In MTR Mobile, select this journey, open Suggested Route → Fast Exit, then choose this exit. An arrival platform is also needed at stations with multiple possible platforms.';r.append(note);let a=document.createElement('a');a.href='https://www.mtr.com.hk/mtrmobile/en/transport/fast-exit/';a.target='_blank';a.rel='noopener';a.textContent='MTR Fast Exit instructions ↗';r.append(a);if(to==='ADM'){const map=document.createElement('a');map.href='https://www.mtr.com.hk/archive/ch/services/layouts/adm.pdf';map.target='_blank';map.rel='noopener';map.textContent='Official Admiralty layout ↗';const info=document.createElement('p');info.textContent='The official layout places East Rail platforms 7/8 on L5 and Exit F on the L1 concourse. It does not label car/door numbers, so it cannot verify an optimal boarding door.';r.append(info,map)}}
$('#doorSave').onclick=()=>{const platform=$('#doorPlatform').value.trim(),number=$('#doorNumber').value.trim(),from=$('#doorFrom').value,to=$('#doorTo').value,exit=$('#doorExit').value.trim().toUpperCase();if(!platform||!number||!exit||from===to){$('#doorSaved').textContent='Choose different stations and enter exit, platform, and car/door.';return}try{localStorage.setItem('boarding-note:'+from+':'+to+':'+exit,JSON.stringify({platform,door:number}));$('#doorSaved').textContent='Saved on this device.';doorResult()}catch{$('#doorSaved').textContent='Storage is unavailable in this browser.'}};
$('#doorCheck').onclick=doorResult;for(const id of ['doorFrom','doorTo','doorExit'])$('#'+id).addEventListener('change',doorResult);
async function openData(){
 data.showModal();const box=data.querySelector('.passenger-content');box.replaceChildren();
 const statusBox=document.createElement('section'),reportBox=document.createElement('section'),eventsBox=document.createElement('section');box.append(eventsBox,reportBox,statusBox);
 statusBox.textContent='Checking collector…';reportBox.textContent='Loading historical evaluation…';
 const paragraph=(parent,text)=>{const p=document.createElement('p');p.textContent=text;parent.append(p)};
 await Promise.allSettled([
  (async()=>{try{const response=await fetch('station_event_report.json',{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error();const e=await response.json();paragraph(eventsBox,'Station-event training · offline experiment');paragraph(eventsBox,`${e.events.toLocaleString()} observed travel/dwell intervals. Latest held-out date: ${e.test_date}.`);for(const kind of ['travel','dwell']){const m=e.test[kind];paragraph(eventsBox,`${kind==='travel'?'Departure → next arrival':'Arrival → departure'}: ${Number.isFinite(m.mae_seconds)?m.mae_seconds.toFixed(1)+' s mean error':'not evaluated'}, ${m.supported_events}/${m.test_events} supported test intervals.`)}paragraph(eventsBox,`${e.one_to_zero_events} explicit 1-minute → 0-minute transitions in this training run. Older archives did not retain the countdown field; recording it is now enabled. A missing train row does not prove departure.`)}catch{paragraph(eventsBox,'Station-event report is unavailable.')}})(),
  (async()=>{try{
   const response=await apiFetch('/api/training/status',{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Unavailable');const status=await response.json();statusBox.replaceChildren();
   paragraph(statusBox,'Collector observations');
   for(const source of status.sources||[])paragraph(statusBox,`${source.kind==='eal'?'East Rail telemetry':'Official ETA'}: ${source.rows.toLocaleString()} rows. Last record: ${new Date(source.newest*1000).toLocaleString('en-GB',{timeZone:'Asia/Hong_Kong'})} HKT.`);
   paragraph(statusBox,'Collection runs while the API server is awake. Continuous collection requires persistent storage and an always-on service.');
  }catch{statusBox.textContent='Collector status unavailable. The historical evaluation above is independent of the live API.'}})(),
  (async()=>{try{
   const response=await fetch('training_report.json',{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Unavailable');const r=await response.json();reportBox.replaceChildren();
   const seconds=n=>Number.isFinite(n)?n.toFixed(1)+' s':'not evaluated';
   paragraph(reportBox,`Historical model · ${r.deployed?'active':'not deployed'}`);
   paragraph(reportBox,`${r.labeled_rows.toLocaleString()} labeled observations, ${r.journeys.toLocaleString()} arrival groups across ${r.days} dates. ${r.dates?.join(', ')||''}`);
   paragraph(reportBox,`Training: ${r.training_dates?.join(', ')||'see report'}. Validation: ${r.validation_dates?.join(', ')||'see report'}. Test: ${r.test_dates?.join(', ')||'see report'}.`);
   paragraph(reportBox,`Held-out mean error: ${seconds(r.test_mae_seconds)}. Learned progress-only baseline: ${seconds(r.test?.progress_baseline_mae_seconds)}. Distance/speed baseline: ${seconds(r.constant_speed_baseline_mae_seconds)}.`);
   paragraph(reportBox,`90th-percentile error: ${seconds(r.test?.p90_error_seconds)}. Model support: ${((r.test?.coverage||0)*100).toFixed(1)}%. Error includes unsupported rows using fallback estimates.`);
   if(Number.isFinite(r.test?.within_one_second_fraction))paragraph(reportBox,`Within one second of the telemetry arrival label: ${(r.test.within_one_second_fraction*100).toFixed(1)}% of latest-test observations. The label itself has observation timing uncertainty.`);
   const back=r.historical_backtests;
   if(back?.folds?.length){paragraph(reportBox,`Earlier-date training tested across ${back.folds.length} later dates: ${seconds(back.mae_seconds)} mean error across ${back.journeys.toLocaleString()} arrival groups. Each test date uses only preceding dates.`);const table=document.createElement('table');table.className='evaluation-table';const caption=document.createElement('caption');caption.textContent='Historical tests by date';table.append(caption);for(const f of back.folds){const row=table.insertRow();row.insertCell().textContent=f.test_date;row.insertCell().textContent=f.journeys+' groups';row.insertCell().textContent=seconds(f.mae_seconds)}reportBox.append(table)}

   if(r.test?.segments){const table=document.createElement('table');table.className='evaluation-table';const caption=document.createElement('caption');caption.textContent='Your direction: Mong Kok East → Admiralty';table.append(caption);for(const name of ['MKK → HUH','HUH → EXC','EXC → ADM']){const metric=r.test.segments[name];if(!metric)continue;const row=table.insertRow();row.insertCell().textContent=name;row.insertCell().textContent=seconds(metric.mae_seconds)+' mean error'}reportBox.append(table)}
   paragraph(reportBox,'Target: time to the first stopped telemetry sample. These are not GPS-position errors or independently measured doors-open times.');
   if(r.review_blockers?.length)paragraph(reportBox,'Not ready for live use: '+r.review_blockers.join('; ')+'.');
  }catch{reportBox.textContent='Historical evaluation could not be loaded.'}})()
 ]);
}
})();
