(()=>{
const $=s=>document.querySelector(s),G=window.V12_GEO;
const nav=document.createElement('nav');nav.className='phone-nav';nav.setAttribute('aria-label','Phone navigation');nav.innerHTML='<button data-view="map" aria-pressed="true">Map</button><button data-view="board" aria-pressed="false">Arrivals</button><button data-view="plan">Journey</button><button data-view="data">Data</button>';document.body.append(nav);
function view(which){document.body.dataset.phoneView=which;nav.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===which)))}
document.addEventListener('station-board-open',()=>view('board'));
nav.onclick=e=>{const v=e.target.dataset.view;if(v==='plan')$('#journeyBtn').click();else if(v==='data')openData();else if(v){view(v);if(v==='board')$('#boardTab').click()}};
const toolbar=$('.explore-bar');const doorButton=document.createElement('button');doorButton.textContent='Best door';doorButton.onclick=openDoor;toolbar.append(doorButton);
const dataButton=document.createElement('button');dataButton.textContent='Prediction data';dataButton.onclick=openData;toolbar.append(dataButton);
function dialog(id,title){let d=document.createElement('dialog');d.id=id;d.className='passenger-dialog';d.innerHTML=`<form method="dialog"><h2>${title}</h2><button aria-label="Close ${title}">×</button></form><div class="passenger-content"></div>`;document.body.append(d);return d}
const door=dialog('doorAdvisor','Best door'),data=dialog('dataPanel','Prediction data');
const options=Object.entries(G.stations).sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([c,s])=>`<option value="${c}">${s.name}</option>`).join('');
door.querySelector('.passenger-content').innerHTML=`<p>Plan for the shortest walk to your chosen exit.</p><label>Starting station<select id="doorFrom">${options}</select></label><label>Destination station<select id="doorTo">${options}</select></label><label>Exit letter / number<input id="doorExit" value="F" maxlength="12" placeholder="e.g. F"></label><button id="doorCheck">Check boarding guidance</button><div id="doorResult" aria-live="polite"></div>`;
$('#doorFrom').value='MKK';$('#doorTo').value='ADM';
function openDoor(){door.showModal();doorResult()}
function doorResult(){const from=$('#doorFrom').value,to=$('#doorTo').value,exit=$('#doorExit').value.trim().toUpperCase(),r=$('#doorResult');r.replaceChildren();let p=document.createElement('p');p.textContent=`${G.stations[from].name} → ${G.stations[to].name} · Exit ${exit||'not selected'}`;r.append(p);let note=document.createElement('p');note.textContent=from===to?'Select a different destination for a train journey.':!exit?'Enter your destination exit.':'Car and door mapping is not verified in this app. In MTR Mobile, select this journey, open Suggested Route → Fast Exit, then choose this exit. An arrival platform is also needed at stations with multiple possible platforms.';r.append(note);let a=document.createElement('a');a.href='https://www.mtr.com.hk/mtrmobile/en/transport/fast-exit/';a.target='_blank';a.rel='noopener';a.textContent='MTR Fast Exit instructions ↗';r.append(a)}
$('#doorCheck').onclick=doorResult;for(const id of ['doorFrom','doorTo','doorExit'])$('#'+id).addEventListener('change',doorResult);
async function openData(){data.showModal();const box=data.querySelector('.passenger-content');box.textContent='Loading collection status…';try{const status=await(await apiFetch('/api/training/status',{signal:AbortSignal.timeout(12000)})).json();box.replaceChildren();const heading=document.createElement('p');heading.textContent='Collection runs on the API server while it is awake. Telemetry observations are archived separately from ETA predictions.';box.append(heading);for(const s of status.sources||[]){const p=document.createElement('p');p.textContent=`${s.kind==='eal'?'East Rail telemetry':'Official ETA'}: ${s.rows.toLocaleString()} observations`;box.append(p)}const note=document.createElement('p');note.textContent='Cloud collection needs persistent storage and an always-on service. A sleeping or redeployed free host cannot guarantee continuous data retention.';box.append(note)}catch{box.textContent='The collection server is unavailable. The historical validation report below is still available.'}
try{const report=await(await fetch('training_report.json')).json();const p=document.createElement('p');p.textContent=`Historical experiment: ${report.labeled_rows.toLocaleString()} labeled rows, ${report.journeys.toLocaleString()} journeys across ${report.days} days. Held-out mean error ${report.test_mae_seconds.toFixed(1)} seconds versus ${report.constant_speed_baseline_mae_seconds.toFixed(1)} seconds for distance/speed. Experimental; not deployed. This predicts a stopped telemetry sample, not an exact physical position.`;box.append(p)}catch{} }
})();
