(()=>{
const D=window.TRAIN_DATA,$=s=>document.querySelector(s);
const profileSel=$('#profile'),clock=$('#clock'),simTimeEl=$('#simTime'),range=$('#timeRange'),markers=$('#markers'),list=$('#trainList'),warning=$('#warningBox'),detail=$('#detail'),detailBody=$('#detailBody');
let profileKey='weekday',simSec=0,playing=true,speed=1,lastTs=performance.now(),lastRender=0,enabled=new Set(Object.keys(D.lines)),selected=null,currentTrips=[];
let mapScale=1,mapX=0,mapY=0,drag=null;const world=$('#mapWorld'),viewport=$('#mapViewport');
const SM=D.speedModel||{},UNITS_PER_KM=SM.distanceScalePdfUnitsPerKm||2942.5;
// Operational snapshot override. This shifts EAL along the timetable time axis; it does not alter the kinematic speed profile.
const LIVE_OVERRIDES={EAL:{delaySec:300,label:'5 min delay',observedAt:'2026-09-09 14:24 HKT',source:'EAL TMS',url:'https://eal-tms.rocteccloud.com/#/layer1'}};
function liveOverride(line){return LIVE_OVERRIDES[line]||null}
function delayFor(line){return liveOverride(line)?.delaySec||0}
function expectedFmt(sec,line){return fmt(sec+delayFor(line))}
function delayLabel(line){let o=liveOverride(line);return o&&o.delaySec?`+${Math.round(o.delaySec/60)} min`:''}
function installOpsStatus(){let host=document.querySelector('.statusrow>div:first-child');if(!host)return;for(const [line,o] of Object.entries(LIVE_OVERRIDES)){if(!o.delaySec)continue;let a=document.createElement('a');a.className='ops-pill';a.href=o.url;a.target='_blank';a.rel='noopener noreferrer';a.title=`${line} operational override observed ${o.observedAt} · open ${o.source}`;a.innerHTML=`<strong>${line} +${Math.round(o.delaySec/60)}m</strong><span>live snapshot · ${o.source}</span>`;host.appendChild(a)}}
function fmt(sec){sec=((Math.floor(sec)%86400)+86400)%86400;let h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=Math.floor(sec%60);return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function hkNow(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Hong_Kong',hour:'2-digit',minute:'2-digit',second:'2-digit',weekday:'short',hour12:false}).formatToParts(new Date());let o={};parts.forEach(p=>o[p.type]=p.value);return {sec:+o.hour*3600+ +o.minute*60+ +o.second,weekday:o.weekday}}
function autoProfile(){let w=hkNow().weekday;return w==='Fri'?'friday':w==='Sat'?'saturday':w==='Sun'?'sunday':'weekday'}
function loadProfileTrips(){let p=D.profiles[profileKey],out=[];for(const [line,sid] of Object.entries(p.lines)){for(const t of D.schedules[sid]||[])out.push(t)}currentTrips=out}
function sourceTrips(){return currentTrips.length}
function buildGraph(line){let g={};for(const path of D.paths[line]||[]){for(let i=0;i<path.length-1;i++){let a=path[i],b=path[i+1];(g[a]??=[]).push(b);(g[b]??=[]).push(a)}}return g}
const graphs={};for(const l of Object.keys(D.lines))graphs[l]=buildGraph(l);const pathCache=new Map(),metricCache=new Map();
function route(line,a,b){let key=line+'|'+a+'|'+b;if(pathCache.has(key))return pathCache.get(key);if(a===b)return [a];let g=graphs[line]||{},q=[[a]],seen=new Set([a]);while(q.length){let p=q.shift(),x=p[p.length-1];for(const n of g[x]||[]){if(seen.has(n))continue;let np=p.concat(n);if(n===b){pathCache.set(key,np);return np}seen.add(n);q.push(np)}}let direct=[a,b];pathCache.set(key,direct);return direct}
function trackPolyline(line,a,b){let tab=(D.trackRoutes||{})[line]||{},p=tab[a+'|'+b];if(p)return p;p=tab[b+'|'+a];return p?[...p].reverse():null}
function routeMetrics(line,a,b){let key=line+'|'+a+'|'+b;if(metricCache.has(key))return metricCache.get(key);let raw=trackPolyline(line,a,b),pts,codes;if(raw&&raw.length>=2){pts=raw.map(q=>({x:q[0],y:q[1]}));codes=[a,b]}else{codes=route(line,a,b).filter(c=>D.stations[c]);if(codes.length<2)codes=[a,b].filter(c=>D.stations[c]);pts=codes.map(c=>D.stations[c])}let lens=[],total=0;for(let i=0;i<pts.length-1;i++){let dx=(pts[i+1].x-pts[i].x)*D.map.width,dy=(pts[i+1].y-pts[i].y)*D.map.height,d=Math.hypot(dx,dy);lens.push(d);total+=d}let m={codes,pts,lens,total,trackFollowing:!!raw};metricCache.set(key,m);return m}
function pathAt(line,a,b,t){let m=routeMetrics(line,a,b);if(m.pts.length<2)return null;let f=Math.max(0,Math.min(1,t)),target=f*m.total,acc=0;for(let i=0;i<m.lens.length;i++){if(target<=acc+m.lens[i]||i===m.lens.length-1){let u=m.lens[i]?((target-acc)/m.lens[i]):0,p=m.pts[i],q=m.pts[i+1];return {x:p.x+(q.x-p.x)*u,y:p.y+(q.y-p.y)*u,pair:[a,b],pairFraction:f,totalPdf:m.total,trackFollowing:m.trackFollowing}}acc+=m.lens[i]}return null}
function accelFor(line){let a=(SM.accelerationMps2||{});return a[line]||a.default||1}
function decelFor(line){let a=(SM.decelerationMps2||{});return a[line]||a.default||1}
function lineCap(line){return (SM.lineMaxKph||{})[line]||80}
function trapezoid(line,dMeters,T,u){if(!(dMeters>0)||!(T>0))return {progress:u,speedKph:0,phase:'stopped',peakKph:0,avgKph:0,scheduleDemand:false};let a=accelFor(line),d=decelFor(line),A=.5*(1/a+1/d),disc=T*T-4*A*dMeters;let V,ta,td,tc,scheduleDemand=false;
 if(disc>=0){V=(T-Math.sqrt(disc))/(2*A);ta=V/a;td=V/d;tc=Math.max(0,T-ta-td)}else{V=2*dMeters/T;ta=T/2;td=T/2;tc=0;scheduleDemand=true}
 let cap=lineCap(line)/3.6;if(V>cap){scheduleDemand=true;V=cap;ta=Math.min(T*.35,V/a);td=Math.min(T*.35,V/d);tc=Math.max(0,T-ta-td)}
 let t=Math.max(0,Math.min(T,u*T)),s=0,v=0,phase='cruise';let profileD=V*(T-.5*(ta+td));let scale=profileD>0?dMeters/profileD:1;
 if(t<ta){v=a*t; s=.5*a*t*t;phase='accelerating'}else if(t<ta+tc){v=V;s=.5*V*ta+V*(t-ta);phase='cruise'}else{let q=t-ta-tc;v=Math.max(0,V-d*q);s=.5*V*ta+V*tc+V*q-.5*d*q*q;phase='braking'}
 s*=scale;v*=scale;let prog=Math.max(0,Math.min(1,s/dMeters));return {progress:prog,speedKph:v*3.6,phase,peakKph:V*scale*3.6,avgKph:dMeters/T*3.6,scheduleDemand}}
function restrictionAt(line,pair,f){let arr=((SM.fixedRestrictions||{})[line]||[]);if(!arr.length)return null;let rev=false,canon=pair;if(pair[0]>pair[1]){} // no lexical assumptions
 let candidates=[];for(const r of arr){let rp=r.pair;if(pair[0]===rp[0]&&pair[1]===rp[1])candidates.push({r,ff:f});else if(pair[0]===rp[1]&&pair[1]===rp[0])candidates.push({r,ff:1-f})}
 if(!candidates.length)return null;let near=candidates.filter(x=>Math.abs(x.r.fraction-x.ff)<=.085);if(!near.length)return null;let lim=Math.min(...near.map(x=>x.r.limit));let best=near.sort((x,y)=>Math.abs(x.r.fraction-x.ff)-Math.abs(y.r.fraction-y.ff))[0].r;return {limit:lim,source:'TD-URL p.76',board:best}}
function stateAt(t,sec){let wallSec=sec,delaySec=delayFor(t[1]);sec=wallSec-delaySec;let p=t[2];if(sec<p[0][1]||sec>p[p.length-1][1])return null;let i=0;while(i<p.length-2&&sec>p[i+1][1])i++;let a=p[i],b=p[i+1],den=b[1]-a[1],u=den?Math.max(0,Math.min(1,(sec-a[1])/den)):0;let met=routeMetrics(t[1],a[0],b[0]),dMeters=met.total/UNITS_PER_KM*1000,kin=trapezoid(t[1],dMeters,Math.max(1,den),u),pos=pathAt(t[1],a[0],b[0],kin.progress);if(!pos)return null;let rest=restrictionAt(t[1],pos.pair,pos.pairFraction),cap=lineCap(t[1]),spd=Math.min(kin.speedKph,cap,rest?rest.limit:Infinity);return{trip:t,line:t[1],a,b,u,pos,overall:(sec-p[0][1])/(p[p.length-1][1]-p[0][1]),speedKph:Math.max(0,spd),modelSpeedKph:kin.speedKph,phase:kin.phase,peakKph:kin.peakKph,avgKph:kin.avgKph,segmentKm:dMeters/1000,restriction:rest,lineCap:cap,scheduleDemand:kin.scheduleDemand,delaySec,wallSec,modelSec:sec}}
function active(){let out=[];for(const t of currentTrips){if(!enabled.has(t[1]))continue;let s=stateAt(t,simSec);if(s)out.push(s)}return out}
function renderMarkers(a){let keep=new Set;for(const s of a){let id=s.line+'-'+s.trip[0]+'-'+s.trip[2][0][1];keep.add(id);let el=document.getElementById('m-'+id);if(!el){el=document.createElement('button');el.className='train-marker';el.id='m-'+id;el.style.background=D.lines[s.line].color;el.innerHTML='<span class="speed-bubble"></span>';el.addEventListener('click',e=>{e.stopPropagation();let cur=currentTrips.find(t=>('m-'+t[1]+'-'+t[0]+'-'+t[2][0][1])===el.id);if(cur)selectTrip(cur)});markers.appendChild(el)}el.style.left=(s.pos.x*100)+'%';el.style.top=(s.pos.y*100)+'%';el.title=`${s.line} ${s.trip[0]} · ${Math.round(s.speedKph)} km/h · ${s.phase}${s.delaySec?` · ${delayLabel(s.line)} operational delay`:''}`;el.querySelector('.speed-bubble').textContent=Math.round(s.speedKph)+' km/h'+(s.delaySec?' · '+delayLabel(s.line):'');el.classList.toggle('selected',selected===s.trip)}for(const el of [...markers.children]){let id=el.id.slice(2);if(!keep.has(id))el.remove()}}
function renderList(a){let q=$('#search').value.trim().toLowerCase();let items=a.filter(s=>!q||s.trip[0].toLowerCase().includes(q)||D.lines[s.line].name.toLowerCase().includes(q)).sort((x,y)=>x.b[1]-y.b[1]).slice(0,180);list.innerHTML=items.length?'':'<div class="empty">No active trains match this view.</div>';for(const s of items){let r=document.createElement('div');r.className='trainRow';r.innerHTML=`<i style="background:${D.lines[s.line].color}"></i><div><b>${s.line} ${s.trip[0]}</b><span>${D.stations[s.a[0]]?.name||s.a[0]} → ${D.stations[s.b[0]]?.name||s.b[0]} · ${s.phase}</span></div><time><b>${Math.round(s.speedKph)} km/h</b><span>${s.delaySec?`${fmt(s.b[1])} → ${expectedFmt(s.b[1],s.line)} <em>${delayLabel(s.line)}</em>`:fmt(s.b[1])}</span></time>`;r.onclick=()=>selectTrip(s.trip);list.appendChild(r)}}
function selectTrip(t){selected=t;let s=stateAt(t,simSec);if(!s){detail.classList.add('hidden');return}let sid=D.profiles[profileKey].lines[t[1]],m=D.scheduleMeta[sid],p=t[2],r=s.restriction;detailBody.innerHTML=`<h2>${D.lines[t[1]].name} · ${t[0]}</h2><div class="sub">Scheduled train / trip · kinematic simulation</div><div class="speedHero"><b>${Math.round(s.speedKph)}</b><span>km/h<br><small>${s.phase}</small></span></div><dl><dt>Modeled max</dt><dd>${s.lineCap} km/h line/rolling-stock ceiling</dd><dt>Current limit</dt><dd>${r?`${r.limit} km/h · ${r.source}`:`${s.lineCap} km/h · no mapped lower limit here`}</dd><dt>Segment</dt><dd>${D.stations[s.a[0]]?.name||s.a[0]} → ${D.stations[s.b[0]]?.name||s.b[0]} · ${s.segmentKm.toFixed(2)} km</dd><dt>Segment avg.</dt><dd>${Math.round(s.avgKph)} km/h required by timetable</dd><dt>Operational delay</dt><dd>${s.delaySec?`<strong class=delayText>${delayLabel(s.line)}</strong> · ${liveOverride(s.line).source} snapshot ${liveOverride(s.line).observedAt}`:'none applied'}</dd><dt>Next timing</dt><dd>${fmt(s.b[1])}${s.delaySec?` scheduled · <strong>${expectedFmt(s.b[1],s.line)} expected</strong>`:''}</dd><dt>From</dt><dd>${D.stations[p[0][0]]?.name||p[0][0]} · ${fmt(p[0][1])}</dd><dt>To</dt><dd>${D.stations[p[p.length-1][0]]?.name||p[p.length-1][0]} · ${fmt(p[p.length-1][1])}</dd></dl>${s.scheduleDemand?'<div class="modelWarn">This timing segment would demand more than the configured kinematic ceiling; displayed speed is capped while position remains timetable-constrained.</div>':''}<div class="progressbar"><i style="width:${Math.max(0,Math.min(100,s.overall*100))}%"></i></div><div class="source">${s.delaySec?`Operational source: <a href="${liveOverride(s.line).url}" target="_blank" rel="noopener noreferrer">${liveOverride(s.line).source}</a> · ${liveOverride(s.line).observedAt}<br>`:''}Source: ${m.file}<br>Effective: ${m.effective||'not extracted'} · ${m.tripCount} parsed trips<br>Acceleration/deceleration uses ${accelFor(t[1]).toFixed(2)} / ${decelFor(t[1]).toFixed(2)} m/s². ${SM.restrictionSource||''}<br>Movement geometry: ${D.trackGeometry?.method||SM.calibration?.movementMethod||'track diagram'}.</div>`;detail.classList.remove('hidden');render()}
function render(){clock.textContent=fmt(hkNow().sec);simTimeEl.textContent=fmt(simSec)+(simSec>=86400?' +1d':'');range.value=Math.max(+range.min,Math.min(+range.max,simSec));let a=active();$('#activeCount').textContent=a.length;$('#sourceCount').textContent=sourceTrips().toLocaleString();renderMarkers(a);renderList(a);if(selected){let s=stateAt(selected,simSec);if(!s)detail.classList.add('hidden')}}
function setProfile(k){profileKey=k;profileSel.value=k;loadProfileTrips();selected=null;detail.classList.add('hidden');let p=D.profiles[k];$('#profileStatus').textContent=p.label+' · '+Object.keys(p.lines).length+' lines · track-following GeoTD geometry';warning.innerHTML=p.warnings.length?'<strong>Coverage notes</strong><br>'+p.warnings.map(x=>x.line+': '+x.text).join('<br>'):'';warning.classList.toggle('show',!!p.warnings.length);buildFilters();render()}
function buildFilters(){let lines=Object.keys(D.profiles[profileKey].lines);enabled=new Set(lines);let box=$('#lineFilters');box.innerHTML='';for(const l of lines){let lab=document.createElement('label');lab.innerHTML=`<input type="checkbox" checked value="${l}"><span style="color:${D.lines[l].color}">●</span>${l}`;lab.querySelector('input').onchange=e=>{e.target.checked?enabled.add(l):enabled.delete(l);render()};box.appendChild(lab)}let leg=$('#legend');leg.innerHTML=lines.map(l=>`<span><i style="background:${D.lines[l].color}"></i>${D.lines[l].name} · max ${(SM.lineMaxKph||{})[l]||80} km/h</span>`).join('')}
for(const [k,p] of Object.entries(D.profiles)){let o=document.createElement('option');o.value=k;o.textContent=p.label;profileSel.appendChild(o)}profileSel.onchange=e=>setProfile(e.target.value);$('#nowBtn').onclick=()=>{simSec=hkNow().sec;setProfile(autoProfile());render()};$('#playBtn').onclick=e=>{playing=!playing;e.currentTarget.textContent=playing?'Pause':'Play'};$('#speed').onchange=e=>speed=+e.target.value;range.oninput=e=>{simSec=+e.target.value;playing=false;$('#playBtn').textContent='Play';render()};$('#search').oninput=render;$('#allLines').onclick=()=>{enabled=new Set(Object.keys(D.profiles[profileKey].lines));document.querySelectorAll('#lineFilters input').forEach(x=>x.checked=true);render()};$('#closeDetail').onclick=()=>{selected=null;detail.classList.add('hidden');render()};
function applyMap(){world.style.transform=`translate(${mapX}px,${mapY}px) scale(${mapScale})`}function zoom(f,cx=viewport.clientWidth/2,cy=viewport.clientHeight/2){let old=mapScale;mapScale=Math.max(.7,Math.min(6,mapScale*f));mapX=cx-(cx-mapX)*(mapScale/old);mapY=cy-(cy-mapY)*(mapScale/old);applyMap()}$('#zoomIn').onclick=()=>zoom(1.25);$('#zoomOut').onclick=()=>zoom(.8);$('#resetMap').onclick=()=>{mapScale=1;mapX=0;mapY=0;applyMap()};viewport.addEventListener('wheel',e=>{e.preventDefault();let r=viewport.getBoundingClientRect();zoom(e.deltaY<0?1.15:.87,e.clientX-r.left,e.clientY-r.top)},{passive:false});viewport.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,mx:mapX,my:mapY};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging')});viewport.addEventListener('pointermove',e=>{if(!drag)return;mapX=drag.mx+e.clientX-drag.x;mapY=drag.my+e.clientY-drag.y;applyMap()});viewport.addEventListener('pointerup',()=>{drag=null;viewport.classList.remove('dragging')});
installOpsStatus();profileKey=autoProfile();simSec=hkNow().sec;setProfile(profileKey);applyMap();function tick(ts){let dt=(ts-lastTs)/1000;lastTs=ts;if(playing){simSec+=dt*speed;if(simSec>100800)simSec=14400}if(ts-lastRender>=250){render();lastRender=ts}requestAnimationFrame(tick)}requestAnimationFrame(tick);
})();
